"use client";

import { useState } from "react";
import { downloadZip } from "client-zip";
import { toast } from "sonner";
import { Download, Loader2, Package } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useFileSystem } from "@/lib/contexts/file-system-context";

// ---------------------------------------------------------------------------
// Boilerplate injected for "Export entire project"
// ---------------------------------------------------------------------------

const BOILERPLATE: Record<string, string> = {
  "package.json": JSON.stringify(
    {
      name: "uigen-export",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "15.3.3",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        tailwindcss: "^4",
        "@tailwindcss/postcss": "^4",
        "lucide-react": "^0.517.0",
        "class-variance-authority": "^0.7.1",
        clsx: "^2.1.1",
        "tailwind-merge": "^3.3.1",
        "@radix-ui/react-slot": "^1.2.3",
        "@radix-ui/react-dialog": "^1.1.14",
        "@radix-ui/react-dropdown-menu": "^2.1.16",
        "@radix-ui/react-tabs": "^1.1.12",
        "@radix-ui/react-separator": "^1.1.7",
        "@radix-ui/react-scroll-area": "^1.2.9",
        "@radix-ui/react-popover": "^1.1.14",
        "@radix-ui/react-label": "^2.1.7",
        "framer-motion": "^12.0.0",
        recharts: "^2.15.0",
        zustand: "^5.0.0",
        "date-fns": "^4.0.0",
        zod: "^3.24.0",
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
      },
    },
    null,
    2
  ),
  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "es2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  ),
  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};

export default config;
`,
  "README.md": `# UIGen Export

Generated by [UIGen](https://github.com/SifisoScS/uigen) — AI React component builder.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.
`,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Root-level config files stay flat; everything else goes under src/ */
const ROOT_FILES = new Set([
  "package.json",
  "tsconfig.json",
  "tsconfig.base.json",
  "tailwind.config.ts",
  "tailwind.config.js",
  "next.config.ts",
  "next.config.js",
  "postcss.config.js",
  "postcss.config.mjs",
  ".eslintrc.json",
  ".gitignore",
  "README.md",
]);

function virtualPathToZipName(virtualPath: string): string {
  const stripped = virtualPath.replace(/^\//, "");
  return ROOT_FILES.has(stripped) ? stripped : `src/${stripped}`;
}

function sanitize(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "uigen-export"
  );
}

/** Build the client-zip file-entry array from a map of virtual-path → content */
function buildFileEntries(
  files: Map<string, string>,
  includeBoilerplate: boolean
): Array<{ name: string; lastModified: Date; input: string }> {
  const now = new Date();
  const usedNames = new Set<string>();
  const entries: Array<{ name: string; lastModified: Date; input: string }> =
    [];

  for (const [virtualPath, content] of files) {
    const name = virtualPathToZipName(virtualPath);
    usedNames.add(name);
    entries.push({ name, lastModified: now, input: content });
  }

  if (includeBoilerplate) {
    for (const [filename, content] of Object.entries(BOILERPLATE)) {
      // Boilerplate never overwrites user files
      if (!usedNames.has(filename)) {
        entries.push({ name: filename, lastModified: now, input: content });
      }
    }
  }

  return entries;
}

/** Trigger a browser download from a Blob */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Delay revoke so browser has time to begin download
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface ExportButtonProps {
  projectName?: string;
}

export function ExportButton({ projectName }: ExportButtonProps) {
  const { getAllFiles, selectedFile } = useFileSystem();
  const [loading, setLoading] = useState(false);

  const baseName = sanitize(projectName ?? "uigen-export");

  async function handleExport(mode: "current" | "full") {
    if (loading) return;

    const allFiles = getAllFiles();

    if (allFiles.size === 0) {
      toast.error("Nothing to export — the project has no files yet.");
      return;
    }

    // Warn on large projects (rough threshold: >50 files or >500 kB total)
    const totalBytes = [...allFiles.values()].reduce(
      (sum, c) => sum + c.length,
      0
    );
    if (allFiles.size > 50 || totalBytes > 500_000) {
      toast.warning(
        "Large project — ZIP generation may be slow in the browser.",
        { duration: 3000 }
      );
    }

    if (mode === "current") {
      const activeFile = selectedFile;
      if (!activeFile) {
        toast.error("No file is currently selected.");
        return;
      }

      // Include the active file + everything in its top-level directory
      const topDir = "/" + activeFile.split("/").filter(Boolean)[0];
      const subset = new Map<string, string>();
      for (const [path, content] of allFiles) {
        if (
          path === activeFile ||
          path.startsWith(topDir + "/") ||
          path === topDir
        ) {
          subset.set(path, content);
        }
      }

      if (subset.size === 0) {
        toast.error("Could not determine the active file subset.");
        return;
      }

      setLoading(true);
      try {
        const entries = buildFileEntries(subset, false);
        const blob = await downloadZip(entries).blob();
        const zipName =
          sanitize(
            activeFile.split("/").filter(Boolean).pop() ?? "component"
          ) + ".zip";
        triggerDownload(blob, zipName);
        toast.success(
          `Exported "${zipName}" — ${subset.size} file${subset.size === 1 ? "" : "s"}`
        );
      } catch (err) {
        console.error("[ExportButton] current export failed", err);
        toast.error("Export failed. Please try again.");
      } finally {
        setLoading(false);
      }
      return;
    }

    // ── Full project export ───────────────────────────────────────────────
    setLoading(true);
    try {
      const entries = buildFileEntries(allFiles, true);
      const blob = await downloadZip(entries).blob();
      const zipName = `${baseName}.zip`;
      triggerDownload(blob, zipName);
      toast.success(
        `Exported "${zipName}" — ${allFiles.size} file${allFiles.size === 1 ? "" : "s"} + boilerplate`
      );
    } catch (err) {
      console.error("[ExportButton] full export failed", err);
      toast.error("Export failed. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="h-8 gap-1.5 text-xs"
          disabled={loading}
          aria-label="Export project as ZIP"
        >
          {loading ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Package className="h-3.5 w-3.5" />
          )}
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-52">
        <DropdownMenuItem
          onSelect={() => handleExport("current")}
          disabled={loading}
          className="gap-2"
        >
          <Download className="h-3.5 w-3.5 text-muted-foreground" />
          Export current component
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuItem
          onSelect={() => handleExport("full")}
          disabled={loading}
          className="gap-2"
        >
          <Package className="h-3.5 w-3.5 text-muted-foreground" />
          Export entire project
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
