/**
 * export-seed-zips.ts
 *
 * Reads all 6 seeded PublicArtifact records from Neon, reconstructs each
 * project's virtual file tree, and writes individual ZIP files to exports/.
 *
 * Run:
 *   DATABASE_URL=<url> npx tsx scripts/export-seed-zips.ts
 *   — or —
 *   npm run db:export-zips
 *
 * Output:
 *   exports/uigen-seed-auth-v1.0.0.zip
 *   exports/uigen-seed-auth-v1.1.0.zip
 *   exports/uigen-seed-auth-v1.2.0.zip
 *   exports/uigen-seed-price-v1.0.0.zip
 *   exports/uigen-seed-price-v1.1.0.zip
 *   exports/uigen-seed-price-v1.2.0.zip
 *   exports/seeded-artifacts-export-summary.md
 */

import { mkdir, writeFile } from "fs/promises";
import path from "path";
import JSZip from "jszip";
import { PrismaClient } from "../src/generated/prisma/index.js";

const prisma = new PrismaClient();

// ── boilerplate (mirrors ExportButton.tsx) ────────────────────────────────────

const BOILERPLATE: Record<string, string> = {
  "package.json": JSON.stringify(
    {
      name: "uigen-export",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev --turbopack",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "15.3.3",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        tailwindcss: "^4",
        "@tailwindcss/postcss": "^4",
        "lucide-react": "^0.517.0",
        "class-variance-authority": "^0.7.1",
        clsx: "^2.1.1",
        "tailwind-merge": "^3.3.1",
        "@radix-ui/react-slot": "^1.2.3",
        "@radix-ui/react-dialog": "^1.1.14",
        "@radix-ui/react-dropdown-menu": "^2.1.16",
        "@radix-ui/react-tabs": "^1.1.12",
        "@radix-ui/react-separator": "^1.1.7",
        "@radix-ui/react-scroll-area": "^1.2.9",
        "@radix-ui/react-popover": "^1.1.14",
        "@radix-ui/react-label": "^2.1.7",
        "framer-motion": "^12.0.0",
        recharts: "^2.15.0",
        zustand: "^5.0.0",
        "date-fns": "^4.0.0",
        zod: "^3.24.0",
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
      },
    },
    null,
    2
  ),
  "tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        target: "es2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: [
        "next-env.d.ts",
        "**/*.ts",
        "**/*.tsx",
        ".next/types/**/*.ts",
      ],
      exclude: ["node_modules"],
    },
    null,
    2
  ),
  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};

export default config;
`,
  "README.md": `# UIGen Export

Generated by [UIGen](https://github.com/SifisoScS/uigen) — AI-powered React component builder.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.
`,
};

// Config files that live at the project root (not under src/)
const ROOT_FILES = new Set([
  "package.json",
  "tsconfig.json",
  "tailwind.config.ts",
  "tailwind.config.js",
  "next.config.ts",
  "next.config.js",
  "postcss.config.js",
  "postcss.config.mjs",
  ".eslintrc.json",
  ".gitignore",
  "README.md",
]);

function virtualPathToZipPath(virtualPath: string): string {
  const stripped = virtualPath.replace(/^\//, "");
  return ROOT_FILES.has(stripped) ? stripped : `src/${stripped}`;
}

// ── file-tree walker ──────────────────────────────────────────────────────────

interface FileNode {
  type: "file" | "directory";
  path?: string;
  content?: string;
  children?: Record<string, FileNode>;
}

function walkTree(node: unknown, files: Map<string, string>) {
  if (!node || typeof node !== "object") return;
  const n = node as FileNode;
  if (n.type === "file" && typeof n.path === "string" && n.content != null) {
    files.set(n.path, n.content);
  }
  if (n.children && typeof n.children === "object") {
    for (const child of Object.values(n.children)) {
      walkTree(child, files);
    }
  }
}

function extractFiles(filesData: string): Map<string, string> {
  const files = new Map<string, string>();
  try {
    const parsed: unknown = JSON.parse(filesData);
    walkTree(parsed, files);
  } catch {
    console.warn("  ⚠ Could not parse filesData");
  }
  return files;
}

// ── ZIP builder ───────────────────────────────────────────────────────────────

async function buildZip(
  files: Map<string, string>,
  artifactName: string
): Promise<Buffer> {
  const zip = new JSZip();
  const usedPaths = new Set<string>();

  // Project files
  for (const [virtualPath, content] of files) {
    const zipPath = virtualPathToZipPath(virtualPath);
    usedPaths.add(zipPath);
    zip.file(zipPath, content);
  }

  // Boilerplate (never overwrites project files)
  for (const [filename, content] of Object.entries(BOILERPLATE)) {
    if (!usedPaths.has(filename)) {
      zip.file(filename, content);
    }
  }

  // Artifact info file
  zip.file(
    ".uigen-artifact.json",
    JSON.stringify({ name: artifactName, exportedAt: new Date().toISOString() }, null, 2)
  );

  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}

// ── filename helpers ──────────────────────────────────────────────────────────

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Maps seed artifact IDs to short family slugs for the filename */
function familySlug(id: string): string {
  if (id.startsWith("seed-auth")) return "auth";
  if (id.startsWith("seed-price")) return "price";
  return slugify(id);
}

function zipFilename(artifact: { id: string; version: string }): string {
  return `uigen-seed-${familySlug(artifact.id)}-v${artifact.version}.zip`;
}

// ── summary markdown ──────────────────────────────────────────────────────────

function buildSummary(
  entries: Array<{
    filename: string;
    artifact: { id: string; name: string; description: string | null; version: string };
    fileCount: number;
  }>
): string {
  const lines: string[] = [
    "# UIGen Seeded Artifacts — Export Summary",
    "",
    `Exported: ${new Date().toUTCString()}`,
    `Source: https://github.com/SifisoScS/uigen`,
    "",
    "---",
    "",
  ];

  for (const { filename, artifact, fileCount } of entries) {
    lines.push(`## ${artifact.name} \`v${artifact.version}\``);
    lines.push("");
    if (artifact.description) lines.push(`> ${artifact.description}`);
    lines.push("");
    lines.push(`- **ZIP:** \`${filename}\``);
    lines.push(`- **Files:** ${fileCount} source file(s) + boilerplate`);
    lines.push(`- **Share:** \`/share/${artifact.id}\``);
    lines.push(`- **Lineage:** \`/lineage/${artifact.id}\``);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("## Running a ZIP locally");
  lines.push("");
  lines.push("```bash");
  lines.push("unzip uigen-seed-auth-v1.0.0.zip -d my-project");
  lines.push("cd my-project");
  lines.push("npm install");
  lines.push("npm run dev");
  lines.push("```");
  lines.push("");
  lines.push("Open http://localhost:3000 to see the component render live.");

  return lines.join("\n");
}

// ── main ──────────────────────────────────────────────────────────────────────

const SEED_IDS = [
  "seed-auth-v1",
  "seed-auth-v2",
  "seed-auth-v3",
  "seed-price-v1",
  "seed-price-v2",
  "seed-price-v3",
];

async function main() {
  const outDir = path.resolve(process.cwd(), "exports");
  await mkdir(outDir, { recursive: true });
  console.log(`Output dir: ${outDir}\n`);

  const artifacts = await prisma.publicArtifact.findMany({
    where: { id: { in: SEED_IDS } },
    orderBy: { createdAt: "asc" },
  });

  if (artifacts.length === 0) {
    console.error(
      "No seed artifacts found in the database. Run `npm run db:seed` first."
    );
    process.exit(1);
  }

  const summaryEntries: Parameters<typeof buildSummary>[0] = [];

  for (const artifact of artifacts) {
    const filename = zipFilename(artifact);
    console.log(`Building ${filename}...`);

    const files = extractFiles(artifact.filesData);
    if (files.size === 0) {
      console.warn(`  ⚠ No files extracted from filesData — skipping`);
      continue;
    }

    const zipBuffer = await buildZip(files, artifact.name);
    const outPath = path.join(outDir, filename);
    await writeFile(outPath, zipBuffer);

    const kb = (zipBuffer.length / 1024).toFixed(1);
    console.log(`  ✓ ${filename} (${files.size} files, ${kb} kB)`);

    summaryEntries.push({ filename, artifact, fileCount: files.size });
  }

  // Write summary markdown
  const summary = buildSummary(summaryEntries);
  const summaryPath = path.join(outDir, "seeded-artifacts-export-summary.md");
  await writeFile(summaryPath, summary, "utf8");
  console.log(`\n✓ seeded-artifacts-export-summary.md`);

  console.log(`\nAll done. Files are in: ${outDir}`);
  console.log("\nNext steps:");
  console.log("  gh release create v0.1.0-seed exports/* --title 'UIGen Demo Seed Artifacts'");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
